Repository landvilleng/landville-frontend, pull requests merged in 2019-08, with the labels that each got.

#15 #167373681 A user should be able to see a home page
  package-lock.json
  src/app/app.component.scss
  src/app/components/footer/footer.component.html
  src/app/components/footer/footer.component.scss
  src/app/components/navbar/navbar.component.html
  src/app/layouts/auth-layout/auth-layout.module.ts
  src/app/layouts/auth-layout/auth-layout.routing.ts
  src/app/layouts/common-layout/common-layout.module.ts
  src/app/layouts/common-layout/common-layout.routing.ts
  src/app/pages/home/home.component.html
  src/app/pages/home/home.component.scss
  src/app/pages/home/home.component.spec.ts
  src/app/pages/home/home.component.ts
  src/assets/img/House Architecture 4.jpg
  src/assets/img/House Architecture 5.jpg
  src/assets/img/House Architecture 6.jpg
  src/assets/img/House Architecture 7.jpg
  src/assets/img/House Architecture 8.jpg
  src/assets/img/House Architecture 9.jpg
  src/assets/img/HouseBG.jpg
  src/assets/img/profile.png
Labels: ready for review

#12 #167128184 Users can view and update their personal information
  angular.json
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/.gitkeep
  src/app/components/footer/footer.component.html
  src/app/components/navbar/navbar.component.html
  src/app/config.ts
  src/app/helpers/spies.ts
  src/app/helpers/unsubscribe.ts
  src/app/layouts/auth-layout/auth-layout.module.ts
  src/app/layouts/common-layout/common-layout.module.ts
  src/app/layouts/common-layout/common-layout.routing.ts
  src/app/models/.gitkeep
  src/app/models/Address.ts
  src/app/models/Profile.ts
  src/app/models/User.ts
  src/app/pages/home/home.component.html
  src/app/pages/login/login.component.spec.ts
  src/app/pages/profile/personal-information/personal-information.component.html
  src/app/pages/profile/personal-information/personal-information.component.scss
  src/app/pages/profile/personal-information/personal-information.component.spec.ts
  src/app/pages/profile/personal-information/personal-information.component.ts
  src/app/pages/profile/profile-sidebar/profile-sidebar.component.html
  src/app/pages/profile/profile-sidebar/profile-sidebar.component.scss
  src/app/pages/profile/profile-sidebar/profile-sidebar.component.spec.ts
  src/app/pages/profile/profile-sidebar/profile-sidebar.component.ts
  src/app/pages/profile/profile.component.html
  src/app/pages/profile/profile.component.scss
  src/app/pages/profile/profile.component.spec.ts
  src/app/pages/profile/profile.component.ts
  src/app/pages/profile/profile.module.ts
  src/app/services/.gitkeep
  src/app/services/local-storage.service.spec.ts
  src/app/services/local-storage.service.ts
  src/app/services/profile/profile.service.spec.ts
  src/app/services/profile/profile.service.ts
  src/app/shared/mocks.ts
  src/app/shared/pipes/role.pipe.ts
  src/assets/scss/components/_button.scss
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/index.html
  src/styles.scss
  tsconfig.app.json
Labels: ready for review

#14 #167164616 Client Admin should be able to add their company
  README.md
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/footer/footer.component.html
  src/app/components/navbar/navbar.component.html
  src/app/config.ts
  src/app/helpers/auth.guard.spec.ts
  src/app/helpers/auth.guard.ts
  src/app/helpers/error.interceptor.spec.ts
  src/app/helpers/error.interceptor.ts
  src/app/helpers/jwt.interceptor.spec.ts
  src/app/helpers/jwt.interceptor.ts
  src/app/helpers/spies.ts
  src/app/layouts/common-layout/common-layout.module.ts
  src/app/layouts/common-layout/common-layout.routing.ts
  src/app/models/company.ts
  src/app/models/index.ts
  src/app/models/login/loginData.ts
  src/app/pages/company/company.component.html
  src/app/pages/company/company.component.scss
  src/app/pages/company/company.component.spec.ts
  src/app/pages/company/company.component.ts
  src/app/pages/home/home.component.html
  src/app/pages/login/login-form/login-form.component.ts
  src/app/pages/registration/registration.component.spec.ts
  src/app/pages/registration/registration.component.ts
  src/app/services/company/company.service.spec.ts
  src/app/services/company/company.service.ts
  src/app/services/login/login.service.ts
  src/assets/img/designs/Design.jpg
  src/assets/scss/base/_base.scss
  src/assets/scss/components/_button.scss
  src/assets/scss/components/_input.scss
  src/assets/scss/main.scss
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: ready for review

#9 #167123375 Users be able to login via social auth
  package-lock.json
  package.json
  src/app/components/components.module.ts
  src/app/config.ts
  src/app/helpers/auth.guard.spec.ts
  src/app/helpers/social.spies.ts
  src/app/helpers/spies.ts
  src/app/layouts/auth-layout/auth-layout.component.spec.ts
  src/app/layouts/auth-layout/auth-layout.component.ts
  src/app/layouts/auth-layout/auth-layout.module.ts
  src/app/layouts/auth-layout/auth-layout.routing.ts
  src/app/pages/SocialAuth/socialauth.component.html
  src/app/pages/SocialAuth/socialauth.component.scss
  src/app/pages/SocialAuth/socialauth.component.spec.ts
  src/app/pages/SocialAuth/socialauth.component.ts
  src/app/pages/login/login-form/login-form.component.spec.ts
  src/app/pages/login/login.component.spec.ts
  src/app/pages/login/social-login/social-login.component.html
  src/app/pages/login/social-login/social-login.component.scss
  src/app/pages/login/social-login/social-login.component.spec.ts
  src/app/pages/login/social-login/social-login.component.ts
  src/app/pages/registration/register-form/register-form.component.html
  src/app/pages/registration/register-form/register-form.component.spec.ts
  src/app/pages/registration/registration.component.html
  src/app/pages/registration/registration.component.spec.ts
  src/app/services/SocialAuth/socialauth.service.spec.ts
  src/app/services/SocialAuth/socialauth.service.ts
  tsconfig.app.json
Labels: ready for review

#13 #167127930 reset user account password
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/helpers/spies.ts
  src/app/layouts/auth-layout/auth-layout.module.ts
  src/app/pages/enter-reset-password/enter-reset-password.component.html
  src/app/pages/enter-reset-password/enter-reset-password.component.scss
  src/app/pages/enter-reset-password/enter-reset-password.component.spec.ts
  src/app/pages/enter-reset-password/enter-reset-password.component.ts
  src/app/pages/login/login-form/login-form.component.html
  src/app/pages/password-reset/password-reset.component.html
  src/app/pages/password-reset/password-reset.component.scss
  src/app/pages/password-reset/password-reset.component.spec.ts
  src/app/pages/password-reset/password-reset.component.ts
  src/app/services/SocialAuth/socialauth.service.spec.ts
  src/app/services/password/enter-reset-password.service.spec.ts
  src/app/services/password/enter-reset-password.service.ts
  src/app/services/password/password-reset.service.spec.ts
  src/app/services/password/password-reset.service.ts
Labels: ready for review

#16 #167392098 A user can view all available properties
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/card/card.component.html
  src/app/components/card/card.component.scss
  src/app/components/card/card.component.spec.ts
  src/app/components/card/card.component.ts
  src/app/components/navbar/navbar.component.html
  src/app/helpers/spies.ts
  src/app/layouts/auth-layout/auth-layout.module.ts
  src/app/layouts/common-layout/common-layout.module.ts
  src/app/layouts/common-layout/common-layout.routing.ts
  src/app/models/Client.ts
  src/app/models/Coordinates.ts
  src/app/models/Property.ts
  src/app/pages/home/home.component.html
  src/app/pages/profile/personal-information/personal-information.component.ts
  src/app/pages/properties/no-properties/no-properties.component.html
  src/app/pages/properties/no-properties/no-properties.component.scss
  src/app/pages/properties/no-properties/no-properties.component.spec.ts
  src/app/pages/properties/no-properties/no-properties.component.ts
  src/app/pages/properties/properties.component.html
  src/app/pages/properties/properties.component.scss
  src/app/pages/properties/properties.component.spec.ts
  src/app/pages/properties/properties.component.ts
  src/app/services/properties/properties.service.ts
  src/app/services/properties/properties.spec.ts
  src/assets/img/arrowL.svg
  src/assets/img/arrowR.svg
  src/assets/img/designs/Design-min.jpg
  src/assets/img/grid.svg
  src/assets/img/list.svg
  src/assets/img/marker.svg
  src/index.html
  tsconfig.json
Labels: ready for review

#25 #167416901 authenticated users can view profile
  src/app/components/components.module.ts
  src/app/components/footer/footer.component.html
  src/app/components/footer/footer.component.scss
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.scss
  src/app/components/navbar/navbar.component.spec.ts
  src/app/components/navbar/navbar.component.ts
  src/app/components/topbar/topbar.component.html
  src/app/components/topbar/topbar.component.scss
  src/app/components/topbar/topbar.component.spec.ts
  src/app/components/topbar/topbar.component.ts
  src/app/layouts/auth-layout/auth-layout.module.ts
  src/app/layouts/auth-layout/auth-layout.routing.ts
  src/app/layouts/common-layout/common-layout.component.html
  src/app/layouts/common-layout/common-layout.component.spec.ts
  src/app/layouts/common-layout/common-layout.component.ts
  src/app/layouts/common-layout/common-layout.module.ts
  src/app/layouts/common-layout/common-layout.routing.ts
  src/app/pages/home/home.component.html
  src/app/pages/login/login-form/login-form.component.spec.ts
  src/app/pages/login/login-form/login-form.component.ts
  src/app/pages/login/login.component.spec.ts
  src/app/pages/login/login.component.ts
  src/app/pages/profile/personal-information/personal-information.component.ts
  src/app/pages/profile/profile.module.ts
  src/app/services/login/login.service.ts
  src/app/services/register/register-service.service.ts
  src/assets/img/people.png
  src/assets/scss/base/_base.scss
  src/assets/scss/components/_input.scss
  src/assets/scss/layout/_footer.scss
  src/assets/scss/layout/_forms.scss
  src/assets/scss/layout/_headers.scss
  src/assets/scss/layout/_navbar.scss
  src/assets/scss/main.scss
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/index.html
  src/styles.scss
Labels: ready for review

#18 #167528341 Add access control to App routes
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.spec.ts
  src/app/components/navbar/navbar.component.ts
  src/app/guards/auth.guard.spec.ts
  src/app/guards/auth.guard.ts
  src/app/guards/no-auth.guard.spec.ts
  src/app/guards/no-auth.guard.ts
  src/app/helpers/auth.guard.spec.ts
  src/app/helpers/auth.guard.ts
  src/app/helpers/spies.ts
  src/app/layouts/auth-layout/auth-layout.routing.ts
  src/app/layouts/common-layout/common-layout.module.ts
  src/app/layouts/common-layout/common-layout.routing.ts
  src/app/pages/home/home.component.html
  src/app/pages/login/login-form/login-form.component.ts
  src/app/services/auth.service.spec.ts
  src/app/services/auth.service.ts
Labels: ready for review

#29 #167416970 Deposit with tokenized card
  angular.json
  karma.conf.js
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.scss
  src/app/components/navbar/navbar.component.spec.ts
  src/app/components/navbar/navbar.component.ts
  src/app/layouts/common-layout/common-layout.module.ts
  src/app/layouts/common-layout/common-layout.routing.ts
  src/app/pages/home/home.component.scss
  src/app/pages/home/home.component.spec.ts
  src/app/pages/payment/payment.component.scss
  src/app/pages/payment/payment.module.ts
  src/app/pages/payment/payment.routing.ts
  src/app/pages/payment/tokenized-card.component.html
  src/app/pages/payment/tokenized-card.component.spec.ts
  src/app/pages/payment/tokenized-card.component.ts
  src/app/pages/profile/personal-information/personal-information.component.spec.ts
  src/app/pages/profile/profile.module.ts
  src/app/services/payment-service.spec.ts
  src/app/services/payment-service.ts
  src/app/validators/payment-validators.ts
  src/environments/environment.prod.ts
  src/favicon.ico
  src/index.html
  src/styles.scss
Labels: ready for review

#26 #167416945 Deposit with card & PIN
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/pages/payment/payment.module.ts
  src/app/pages/payment/payment.routing.ts
  src/app/pages/payment/pin-payment.component.html
  src/app/pages/payment/pin-payment.component.spec.ts
  src/app/pages/payment/pin-payment.component.ts
  src/app/pages/payment/pin-validate.component.html
  src/app/pages/payment/pin-validate.component.spec.ts
  src/app/pages/payment/pin-validate.component.ts
Labels: approved, ready for review

#37 167994128 view trending properties
  package-lock.json
  src/app/pages/home/home.component.html
  src/app/pages/home/home.component.scss
  src/app/pages/home/home.component.spec.ts
  src/app/pages/home/home.component.ts
Labels: ready for review

#20 #167613413 Integrate code climate
  README.md
Labels: ready for review

#24 #166949157 Enable users to accept terms of use on registration
  .gitignore
  package-lock.json
  src/app/app.module.ts
  src/app/components/components.module.ts
  src/app/components/footer/footer.component.html
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.ts
  src/app/layouts/common-layout/common-layout.routing.ts
  src/app/models/Term.ts
  src/app/pages/SocialAuth/socialauth.component.html
  src/app/pages/SocialAuth/socialauth.component.scss
  src/app/pages/SocialAuth/socialauth.component.spec.ts
  src/app/pages/SocialAuth/socialauth.component.ts
  src/app/pages/enter-reset-password/enter-reset-password.component.html
  src/app/pages/login/login-form/login-form.component.html
  src/app/pages/login/login-form/login-form.component.scss
  src/app/pages/login/login-header/login-header.component.html
  src/app/pages/login/login-slider/login-slider.component.html
  src/app/pages/login/login.component.html
  src/app/pages/login/login.component.scss
  src/app/pages/login/login.component.ts
  src/app/pages/password-reset/password-reset.component.html
  src/app/pages/registration/register-form/register-form.component.html
  src/app/pages/registration/register-form/register-form.component.scss
  src/app/pages/registration/register-form/register-form.component.spec.ts
  src/app/pages/registration/register-form/register-form.component.ts
  src/app/pages/registration/register-header/register-header.component.html
  src/app/pages/registration/register-header/register-header.component.scss
  src/app/pages/registration/registration.component.html
  src/app/pages/registration/registration.component.ts
  src/app/pages/terms/terms.component.html
  src/app/pages/terms/terms.component.scss
  src/app/pages/terms/terms.component.spec.ts
  src/app/pages/terms/terms.component.ts
  src/app/services/SocialAuth/socialauth.service.spec.ts
  src/app/services/SocialAuth/socialauth.service.ts
  src/app/services/login/login.service.spec.ts
  src/app/services/terms/terms.service.spec.ts
  src/app/services/terms/terms.service.ts
  src/assets/btn_google_signin.png
  src/assets/btn_google_signin_dark_normal_web.png
  src/index.html
Labels: approved

#23 #165826906 view property details
  package-lock.json
  src/app/components/card/card.component.html
  src/app/components/card/card.component.ts
  src/app/helpers/spies.ts
  src/app/layouts/common-layout/common-layout.module.ts
  src/app/layouts/common-layout/common-layout.routing.ts
  src/app/models/property-detail/.gitkeep
  src/app/models/property-detail/Address.ts
  src/app/models/property-detail/Client.ts
  src/app/models/property-detail/Coordinates.ts
  src/app/models/property-detail/Property-detail.ts
  src/app/pages/properties/properties.component.html
  src/app/pages/properties/properties.component.spec.ts
  src/app/pages/properties/properties.component.ts
  src/app/pages/property-details/client-admin/client-admin.component.html
  src/app/pages/property-details/client-admin/client-admin.component.scss
  src/app/pages/property-details/client-admin/client-admin.component.spec.ts
  src/app/pages/property-details/client-admin/client-admin.component.ts
  src/app/pages/property-details/property-description/property-description.component.html
  src/app/pages/property-details/property-description/property-description.component.scss
  src/app/pages/property-details/property-description/property-description.component.spec.ts
  src/app/pages/property-details/property-description/property-description.component.ts
  src/app/pages/property-details/property-detail/property-detail.component.html
  src/app/pages/property-details/property-detail/property-detail.component.scss
  src/app/pages/property-details/property-detail/property-detail.component.spec.ts
  src/app/pages/property-details/property-detail/property-detail.component.ts
  src/app/pages/property-details/property-details.component.html
  src/app/pages/property-details/property-details.component.scss
  src/app/pages/property-details/property-details.component.spec.ts
  src/app/pages/property-details/property-details.component.ts
  src/app/pages/property-details/property-details.module.ts
  src/app/services/http.service.ts
  src/app/services/property-detail/property-detail.service.spec.ts
  src/app/services/property-detail/property-detail.service.ts
Labels: ready for review

#31 #165826464 disable user's ability to download pictures
  package-lock.json
  src/assets/scss/base/_base.scss
Labels: ready for review

#19 #167416898 Enable authenticated users make payments using international cards
  package-lock.json
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.scss
  src/app/layouts/auth-layout/auth-layout.routing.ts
  src/app/layouts/common-layout/common-layout.module.ts
  src/app/layouts/common-layout/common-layout.routing.ts
  src/app/models/index.ts
  src/app/models/internationalPayment.ts
  src/app/pages/enter-reset-password/enter-reset-password.component.spec.ts
  src/app/pages/home/home.component.html
  src/app/pages/password-reset/password-reset.component.spec.ts
  src/app/pages/payment/international-payment-status/international-payment-status.component.html
  src/app/pages/payment/international-payment-status/international-payment-status.component.scss
  src/app/pages/payment/international-payment-status/international-payment-status.component.spec.ts
  src/app/pages/payment/international-payment-status/international-payment-status.component.ts
  src/app/pages/payment/international-payment/international-payment.component.html
  src/app/pages/payment/international-payment/international-payment.component.scss
  src/app/pages/payment/international-payment/international-payment.component.spec.ts
  src/app/pages/payment/international-payment/international-payment.component.ts
  src/app/pages/payment/payment.module.ts
  src/app/pages/payment/payment.routing.ts
  src/app/pages/payment/pin-payment.component.html
  src/app/pages/payment/pin-payment.component.ts
  src/app/pages/payment/pin-validate.component.html
  src/app/pages/payment/pin-validate.component.ts
  src/app/pages/payment/tokenized-card.component.html
  src/app/pages/payment/tokenized-card.component.ts
  src/app/services/SocialAuth/socialauth.service.spec.ts
  src/app/services/payment/payment-service.spec.ts
  src/app/services/payment/payment-service.ts
  src/app/shared/input-errors/input-errors.component.html
  src/app/shared/input-errors/input-errors.component.scss
  src/app/shared/input-errors/input-errors.component.spec.ts
  src/app/shared/input-errors/input-errors.component.ts
  src/assets/img/ICON/failure.png
  src/assets/img/ICON/success.png
Labels: ready for review

#33 #167994793 SetUp an issue and PR template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready for review

#27 #167193827 Enables User to view financial status on profile
  package.json
  src/app/components/navbar/navbar.component.html
  src/app/config.ts
  src/app/helpers/spies.ts
  src/app/pages/company/company.component.html
  src/app/pages/home/home.component.html
  src/app/pages/home/home.component.scss
  src/app/pages/profile/financial-information/financial-information.component.html
  src/app/pages/profile/financial-information/financial-information.component.scss
  src/app/pages/profile/financial-information/financial-information.component.spec.ts
  src/app/pages/profile/financial-information/financial-information.component.ts
  src/app/pages/profile/profile.component.html
  src/app/pages/profile/profile.module.ts
  src/app/services/http.service.ts
  src/app/services/profile/profile.service.ts
  src/app/shared/mocks.ts
  src/environments/environment.ts
Labels: approved

#34 167648129 Enable Users to retrieve their deposits
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/footer/footer.component.html
  src/app/components/navbar/navbar.component.html
  src/app/helpers/spies.ts
  src/app/layouts/common-layout/common-layout.module.ts
  src/app/layouts/common-layout/common-layout.routing.ts
  src/app/models/Deposit.ts
  src/app/pages/deposits/deposits.component.html
  src/app/pages/deposits/deposits.component.scss
  src/app/pages/deposits/deposits.component.spec.ts
  src/app/pages/deposits/deposits.component.ts
  src/app/pages/properties/properties.component.spec.ts
  src/app/services/deposits/deposits.service.spec.ts
  src/app/services/deposits/deposits.service.ts
  src/environments/environment.ts
  src/index.html
  src/styles.scss
Labels: ready for review
