Repository landvilleng/landville-frontend, pull requests merged in 2019-07, with the labels that each got.

#3 #167132823 Configure CircleCI with the frontend repository
  .circleci/config.yml
  .editorconfig
  .gitignore
  angular.json
  browserslist
  e2e/protractor.conf.js
  e2e/src/app.e2e-spec.ts
  e2e/src/app.po.ts
  e2e/tsconfig.json
  karma.conf.js
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/assets/.gitkeep
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/favicon.ico
  src/index.html
  src/main.ts
  src/polyfills.ts
  src/styles.scss
  src/test.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.spec.json
  tslint.json
Labels: work in progress

#5 #167204518 Fix workspace error on boilerplate
  README.md
  angular.json
  karma.conf.js
  src/index.html
Labels: ready for review

#8 #167246164 layout blueprint setup
  README.md
  angular.json
  app.json
  e2e/protractor.conf.js
  e2e/src/app.e2e-spec.ts
  e2e/src/app.po.ts
  karma.conf.js
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/components/components.module.ts
  src/app/components/footer/footer.component.html
  src/app/components/footer/footer.component.scss
  src/app/components/footer/footer.component.spec.ts
  src/app/components/footer/footer.component.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.scss
  src/app/components/navbar/navbar.component.spec.ts
  src/app/components/navbar/navbar.component.ts
  src/app/layouts/auth-layout/auth-layout.component.html
  src/app/layouts/auth-layout/auth-layout.component.scss
  src/app/layouts/auth-layout/auth-layout.component.spec.ts
  src/app/layouts/auth-layout/auth-layout.component.ts
  src/app/layouts/auth-layout/auth-layout.module.ts
  src/app/layouts/auth-layout/auth-layout.routing.ts
  src/app/layouts/common-layout/common-layout.component.html
  src/app/layouts/common-layout/common-layout.component.scss
  src/app/layouts/common-layout/common-layout.component.spec.ts
  src/app/layouts/common-layout/common-layout.component.ts
  src/app/layouts/common-layout/common-layout.module.ts
  src/app/layouts/common-layout/common-layout.routing.ts
  src/app/models/.gitkeep
  src/app/pages/home/home.component.html
  src/app/pages/home/home.component.scss
  src/app/pages/home/home.component.spec.ts
  src/app/pages/home/home.component.ts
  src/app/pages/login/login.component.html
  src/app/pages/login/login.component.scss
  src/app/pages/login/login.component.spec.ts
  src/app/pages/login/login.component.ts
  src/app/services/.gitkeep
  src/assets/img/icons/logo.png
  src/assets/scss/abstract/_variables.scss
  src/assets/scss/base/_base.scss
  src/assets/scss/components/_button.scss
  src/assets/scss/layout/_footer.scss
  src/assets/scss/layout/_navbar.scss
  src/assets/scss/main.scss
  src/index.html
  src/main.ts
  src/polyfills.ts
  src/test.ts
Labels: enhancement, question, ready for review

#4 #167132855 Integrate Landville-frontend with coveralls
  .circleci/config.yml
  .coveralls.yml
  README.md
  package-lock.json
  package.json
Labels: ready for review

#6 #167205870 Set up storybook
  .storybook/addons.js
  .storybook/config.js
  .storybook/tsconfig.json
  .storybook/typings.d.ts
  angular.json
  package-lock.json
  package.json
  src/app/components/.gitkeep
  src/assets/img/Logo 02.png
  src/assets/img/Logo Icon.png
  src/assets/img/Logo.png
  src/assets/scss/abstracts/_variables.scss
  src/assets/scss/base/_base.scss
  src/assets/scss/layout/_forms.scss
  src/assets/scss/layout/_headers.scss
  src/stories/index.stories.ts
  src/styles.scss
  tsconfig.app.json
Labels: ready for review

#7 #167193186 Deploy Base Frontend to Heroku
  README.md
  package-lock.json
  package.json
  server.js
Labels: ready for review

#11 #167123181 User Login On Frontend
  package-lock.json
  package.json
  src/app/app.component.scss
  src/app/app.module.ts
  src/app/components/footer/footer.component.html
  src/app/config.ts
  src/app/helpers/spies.ts
  src/app/layouts/auth-layout/auth-layout.module.ts
  src/app/layouts/auth-layout/auth-layout.routing.ts
  src/app/models/login/loginData.ts
  src/app/pages/login/login-form/login-form.component.html
  src/app/pages/login/login-form/login-form.component.scss
  src/app/pages/login/login-form/login-form.component.spec.ts
  src/app/pages/login/login-form/login-form.component.ts
  src/app/pages/login/login-header/login-header.component.html
  src/app/pages/login/login-header/login-header.component.scss
  src/app/pages/login/login-header/login-header.component.spec.ts
  src/app/pages/login/login-header/login-header.component.ts
  src/app/pages/login/login-slider/login-slider.component.html
  src/app/pages/login/login-slider/login-slider.component.scss
  src/app/pages/login/login-slider/login-slider.component.spec.ts
  src/app/pages/login/login-slider/login-slider.component.ts
  src/app/pages/login/login.component.html
  src/app/pages/login/login.component.scss
  src/app/pages/login/login.component.spec.ts
  src/app/pages/login/login.component.ts
  src/app/pages/login/social-login/social-login.component.html
  src/app/pages/login/social-login/social-login.component.scss
  src/app/pages/login/social-login/social-login.component.spec.ts
  src/app/pages/login/social-login/social-login.component.ts
  src/app/services/http.service.spec.ts
  src/app/services/http.service.ts
  src/app/services/login/login.service.spec.ts
  src/app/services/login/login.service.ts
  src/assets/images/House Architecture 4.jpg
  src/assets/images/ICON/Email.png
  src/assets/images/ICON/Facebook.png
  src/assets/images/ICON/LinkedIn.png
  src/assets/images/ICON/Login Slider Image.png
  src/assets/images/ICON/Login.png
  src/assets/images/ICON/Logo 02.png
  src/assets/images/ICON/Logo Icon.png
  src/assets/images/ICON/Logo.png
  src/favicon.ico
  src/styles.scss
  tsconfig.app.json
Labels: ready for review
